version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9

    working_directory: ~/react-chart-editor

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  percy:
    docker:
      - image: circleci/node:8.9

    working_directory: ~/react-chart-editor

    branches:
      # only from canonical repository, not pull requests from forks
      only: /^(?!pull\/).*$/
        
    steps:
      - run: npm run test:percy
