version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.2-browsers

    working_directory: ~/react-chart-editor

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - run: npm run test:percy
