const ACTIONS = {
  EDITOR_UPDATE: 'EDITOR_UPDATE',
  INITIALIZE_PLOT: 'INITIALIZE_PLOT',
  PLOT_UPDATE: 'PLOT_UPDATE',
  UPDATE_SOURCES: 'UPDATE_SOURCES',
  UPDATE_SOURCE_OPTIONS: 'UPDATE_SOURCE_OPTIONS',
};

export default ACTIONS;
